site_name: Madhusudansingh Rathore Portfolio
site_description: Portfolio of Madhusudansingh Rathore
site_url: https://themadhu.dev
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep orange
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
plugins:
  - search
  # - blog
  - meta
  - social

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js
