import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // documentationSidebar: [{type: 'autogenerated', dirName: '.'}],
  documentationSidebar: [
    {
      type: 'category',
      label: 'NGINX',
      link: {
        type: 'doc',
        id: 'nginx/intro',
      },
      items: [
        {
          type: 'doc',
          label: 'Setup',
          id: 'nginx/setup',
        },
        {
          type: 'doc',
          label: 'Rate Limiting',
          id: 'nginx/rate-limiting',
        },
        {
          type: 'doc',
          label: 'Logging',
          id: 'nginx/logging',
        },
      ],
    }
  ],
};

export default sidebars;
