import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // portfolioSidebar: [{type: 'autogenerated', dirName: '.'}],
  portfolioSidebar: [
    {
      type: 'category',
      label: 'Revise Network',
      link: {
        type: 'doc',
        id: 'revise-network/intro',
      },
      items: [
        {
          type: 'doc',
          label: 'Browser Extension',
          id: 'revise-network/browser-extension',
        },
        {
          type: 'doc',
          label: 'Alteria VC',
          id: 'revise-network/alteria-vc',
        },
      ],
    }
  ],
};

export default sidebars;
